$title = "Storage Report"
$subtitle = "Hard drive space"
$date = Get-Date -DisplayHint Date | Out-String
$owner = "@Fernan.A.Lopez"
$htmlFile = "C:\users\kc896ha\downloads\diskSpace_Server.html"
$disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object Size, FreeSpace | ConvertTo-Html -Title "$title" -PreContent "<p><font size=`"6`">$title</font><br>$subtitle</p><P><font size=`"2`">Generated by $owner on $date</font></P><hr>" -post "<hr><font size=`"2`">For details, contact $owner.</font>" > $htmlFile
Invoke-Item $htmlFile

write-host ($disk.size / 1gb) | Out-File -Append -FilePath desktop\disk.txt
Write-Host ("{0}GB total" -f [math]::truncate($disk.Size / 1GB))
Write-Host ("{0}GB free" -f [math]::truncate($disk.FreeSpace / 1GB))
