<#
#>
$Computers = Get-ADComputer -Filter * -SearchBase "fill in with your domain info" | select-object -expandproperty dnshostname
$title = "Server Storage Report"
$subtitle = "Hard drive space on servers"
$date = Get-Date -DisplayHint Date | Out-String
$owner = "Company IT"
$htmlFile = "C:\scripts\reports\diskSpace_Server.html"
Get-WmiObject Win32_LogicalDisk -ComputerName $Computers -Filter "DriveType='3'" -ErrorAction SilentlyContinue | Select-Object PsComputerName, DeviceID, @{N="Disk Size (GB) ";e={[math]::Round($($_.Size) / 1073741824,2)}}, @{N="Free Space (GB)";e={[math]::Round($($_.FreeSpace) / 1073741824,2)}}, @{N="Used Space (%)";e={[math]::Round($($_.Size - $_.FreeSpace) / $_.Size * 100,1)}}, @{N="Used Space (GB)";e={[math]::Round($($_.Size - $_.FreeSpace) / 1073741824,2)}} | Sort-Object -Property 'Used Space (%)' -Descending | ConvertTo-Html -Title "$title" -PreContent "<p><font size=`"6`">$title</font><br>$subtitle</p><P><font size=`"2`">Generated by $owner on $date</font></P><hr>" -post "<hr><font size=`"2`">For details, contact $owner.</font>" > $htmlFile
Invoke-Item $htmlFile